### ISSUE TITLE
Recreate the site!

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/huntresscpa-2.0#1]
Go to huntresscpa.com and review it.  

You'll need to crop the logo and re-use the bg image of the courthouse somehow. 

Then decide if you want to use the law template to redesign it or the other default template we've been using. 

Be sure to include all the same content and functionality (contact form, FAQ, etc).

As always, please create a gh-pages branch as well and be sure to merge it from master consistently.

due:
8-24-15    2p

**Comment by vanderbeam** [comment]
I've pushed the most basic commit with very little deviation from the law template: http://editllc.github.io/huntresscpa-2.0/. Now that I have all the information in there I can focus on the css and incorporating the logo in another place or two (https://github.com/EditLLC/huntresscpa-2.0/blob/master/images/logo.png; which was available in the source so no cropping necessary). 

I plan on changing the font, changing the font size of the links there, adding a dynamic effect here and there, touching up the headers, redoing the nav bar, and maybe a couple more of those stock photos from her original site (along with a few other things)

Which also reminds me of another question... I found the same photo of the courthouse she uses on her website as the cover photo (which I've also incorporated). I found it here: http://familypedia.wikia.com/wiki/Fresno,_California. Are we at risk of violating copyright? 

If there's anything that sticks out to you that you want changed, let me know.

**Comment by rodneystrong** [comment]
Great update Meg, 'preciate this. 

In terms of the image, I'll defer to @irms for comment here. Glad that you found it and brought it up. The site, along with the choices in imagery, was created before I took over so I couldn't tell you where we got that from or if explicit permission was given. 
However, like you imply, better safe than sorry.

**Comment by rodneystrong** [comment]
Did a bit of digging and it turns out wikia enforces different licensing by the image holders. Put simply, there is no blanket copyright rule on all images; each have to looked into for their individual usage by 3rd parties. 

That being said, the license for that specific image is spelled out for us on this page: http://familypedia.wikia.com/wiki/File:RobertCoyleCourthouse.jpg

Essentially we have to attribute the image to the original author (in this case, Cadking3) somewhere on the site. I imagine we'll write a link to the author in the footer. Cadking3 links here on wikimedia: https://commons.wikimedia.org/w/index.php?title=User:Cadking3&action=edit&redlink=1

**Comment by vanderbeam** [comment]
I toyed with it over the weekend but as you can see it's not much different than the original commit. I tried adding the photos but the space is just too small. Let me know what you think.

**Comment by rodneystrong** [comment]
I understand, and nicely done! I like how you designed the title of each section (with the horizontal line centered and the title itself being boxed. 

I also really like that subtle line you have in the top header area underneath "The firm where everybody counts". It's a bit of a mismatched style given how the rest of the site has solid stroked lines and no fading, but let's leave it in for now and see how the client takes it.
