### ISSUE TITLE
Issues the client found

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/huntresscpa-2.0#10]
"
- Under "We're here for you"... the first two paragraphs are more about the firm and less about me individually.  Can we move those above the title for this section and make them their own section titled "Jennifer Huntress, CPA"  Then you can take the Certified Public Accountant line out below my name.

- Under FAQ's, I don't know where "What if I can't find an attorney?" came from.
"

due:
9-24-15  11a

**Comment by vanderbeam** [comment]
@rodneystrong Did I understand the instructions correctly?
http://editllc.github.io/huntresscpa-2.0/

**Comment by rodneystrong** [comment]
Seems like it! I'll double-check with client. 

Good work! Thanks for the speedy effort
