### ISSUE TITLE
"Contact us" section

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/huntresscpa-2.0#2]
The line extends the full width while the rest of the lines don't. 

Either make them all extend full width or fix this one

![line](https://cloud.githubusercontent.com/assets/539962/9451706/0a2a6584-4a65-11e5-8dc4-263ee0867b52.jpg)

due:
8-24-15   10p

**Comment by vanderbeam** [comment]
Aaaaaaand done

**Comment by rodneystrong** [comment]
Good job!
