### ISSUE TITLE
Change color of "Send" button in contact form

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/huntresscpa-2.0#4]
Change it to the burgundy color that's being used on the rest of the site and add an HTML double right arrow after the word "send". Make sure you use the HTML version and not just a double greater than sign like this  >>  

due:
8-24-15   10p

**Comment by vanderbeam** [comment]
Let me know if what I did is what you had in mind

**Comment by rodneystrong** [comment]
It is; good job!
