### ISSUE TITLE
Attribution text for photo

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/huntresscpa-2.0#6]
As we discussed in #1 , we'll need to include an attribution link to the author of the photo.

"Essentially we have to attribute the image to the original author (in this case, Cadking3) somewhere on the site. I imagine we'll write a link to the author in the footer. Cadking3 links here on wikimedia: https://commons.wikimedia.org/w/index.php?title=User:Cadking3&action=edit&redlink=1"

In the bottom of the site next to the "&copy; 2015"  put this text:

fresno courthouse photo by Cadking3 

And have the text "Cadking3" linked to the URL I have above.

due:
8-24-15   10p

**Comment by vanderbeam** [comment]
You have to have a Wikipedia user to see it, but it's done

**Comment by rodneystrong** [comment]
Obviously. Thanks for creating the link.

Having the attribution vs not having the attirubtion (or in this case, at least showing an effort to attribute properly) is a no-brainer.
