### ISSUE TITLE
Resizing issues

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/huntresscpa-2.0#8]
While the site responds to the browser width, it doesn't respond in a way that enhances the user experience on the phone. 

![screen shot 2015-08-25 at 2 18 51 am](https://cloud.githubusercontent.com/assets/539962/9463196/eee4c056-4acf-11e5-8c46-603a3e235526.png)

If you look at the site on your phone or at the attached screenshot, you'll notice that the font is difficult to read.

Go through your code and change all your 'col-sm-x' where "x" is equal to whatever number you have there, and replace it with 'col-md-x'. 

This will make it so the content takes up 12 columns on phone screens, making it easier to view. 

due:
8-25-15  9p

**Comment by vanderbeam** [comment]
Done

**Comment by rodneystrong** [comment]
thank yoooou!
